"""add_user_role_v2

Revision ID: c4a7ba66d796
Revises: 002_seed_plans
Create Date: 2026-03-10 03:38:39.813025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4a7ba66d796'
down_revision = '002_seed_plans'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'plan_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('users', sa.Column('role', sa.String(length=20), server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.alter_column('payments', 'plan_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
